# Generated by Django 2.1.2 on 2018-11-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20181111_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assigntime',
            unique_together=set(),
        ),
    ]
