# Generated by Django 4.1.2 on 2022-10-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_remove_student_dob_student_email_teacher_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
